create table public.lesson_signups (
  id bigint generated by default as identity primary key,
  name text not null,
  email text not null,
  notes text,
  created_at timestamptz not null default now()
);

alter table public.lesson_signups enable row level security;

create policy "Anyone can request a lesson"
  on public.lesson_signups
  for insert
  to anon, authenticated
  with check (true);

grant insert on table public.lesson_signups to anon, authenticated;
